### ISSUE TITLE
问题 | 进展 | 完成时间

### ISSUE THREAD

**Issue by Stevenzwzhai** [Tencent/feflow#102]
问题 | 进展 | 完成时间
-- | -- | --
插件/套件中未注入feflow实例 |  进行中  |  
插件/套件初始化失败 |  进行中  | 
help命令未注册倒是运行报错 |  进行中  |
bin命令设置有问题，未指向index.js | 进行中
feflow实例的args为空 | 进行中

**Comment by Stevenzwzhai** [comment]
update

**Comment by cpselvis** [comment]
统一放在https://github.com/Tencent/feflow/issues/101跟进
