### ISSUE TITLE
我自己弄了个脚手架， 自己电脑可以用fe init看到模板；怎么让团队里面的其他人fe init也能看到呢？

### ISSUE THREAD

**Issue by xbcc123** [Tencent/feflow#118]

**Comment by cpselvis** [comment]
嗯，这个是需要团队的同学使用前安装：

$ fef install <template>

安装完成后就有了。比如：

![image](https://user-images.githubusercontent.com/18289264/68005317-d2587680-fcaf-11e9-8c32-0a045e7ea499.png)

**Comment by xbcc123** [comment]
我试试 有没有啥交流群呀

**Comment by cpselvis** [comment]
有的，可以加群进行讨论：

![image](https://user-images.githubusercontent.com/18289264/68110522-22417280-ff28-11e9-9728-331424ae40b7.png)
