### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by cejako** [Tencent/feflow#123]
## For BUG

执行`feflow build`时，报错，如下图：
![image](https://user-images.githubusercontent.com/10059127/68749616-80153f00-0639-11ea-9c3d-e8473fb02826.png)

构建器：
`builderType`: `builder-webpack3`

**Comment by cpselvis** [comment]
这个是实际业务构建包里，使用的项目没有配置 outDir 导致的，和 Feflow 功能无关，已排查解决。
