### ISSUE TITLE
服务器部署需要手动指定 package manager

### ISSUE THREAD

**Issue by codetker** [Tencent/feflow#124]
## For BUG

![image](https://user-images.githubusercontent.com/9033585/68837837-6981ed00-06f8-11ea-88d9-7f2820393448.png)

然后就部署失败了。。。

**Comment by cpselvis** [comment]
v0.16.0-beta.8 版本已经支持，对应的 commit: https://github.com/Tencent/feflow/commit/b68df160e4ba7c1e06e9e05f255d3d6d1bde1d27 https://github.com/Tencent/feflow/commit/bdcea1654bfa6934128d3b7f15d807315c920822
