### ISSUE TITLE
希望feflow能够支持增加子命令选项的描述

### ISSUE THREAD

**Issue by Tingglelaoo** [Tencent/feflow#150]
## For feature request

目前（截至v0.16.0-beta.4），对于子命令的描述可以通过 devkit.json 进行修改，但是若增加子命令的选项（options）时，虽然可以直接从 ctx.args 获取到选项的值，但是想要增加对选项的描述则无从下手，例如 `fef dev -p 1234`，要怎样才能告诉用户` -p `的含义呢？

经过研究，发现只能通过项目文档补充说明，或者是额外引入yargs来弥补这一块的缺陷。但希望能够从官方渠道来增加「支持对选项进行描述」的功能，这样直接从CLI层去提示用户是体验更好的。

**Comment by cpselvis** [comment]
预计在 v0.18.0 版本进行支持

**Comment by fXy-during** [comment]
为套件devkit.json增加新的字段`optionsDescription`.

```json
{
    "build": {
      "implementation": "./src/builder/build",
      "description": "本地构建",
      "optionsDescription": {
        "p": "选择端口构建",
        "dir": "构建产出目录",
        "help": {
          "description": "Display this usage guide.",
          "alias": "h",
          "type": "Boolean"
        }
      }
    }
}
```
可以为套件子命令提供描述，描述支持`string`和`object`类型。
`object`类型支持以下几个字段:
* description. 当前子命令的描述
* alias. 自命令参数别名
* type. 子命令参数类型，默认为`string`类型

`string`类型同description。

运行效果如图：

![image.png](https://qpic.url.cn/feeds_pic/Q3auHgzwzM5xUvDMLKVRhrTibfKPKCYLNibPqaYD8spVW8eic1dt6pJGA/)
