### ISSUE TITLE
希望可以集成yeoman生成脚手架的功能

### ISSUE THREAD

**Issue by ovmahzhao** [Tencent/feflow#155]

**Comment by cpselvis** [comment]
这个跟着 0.18.0 版本， Feflow 提供脚手架、开发套件、开发插件的目录初始化能力已经本地更加友好的调试能力

**Comment by cpselvis** [comment]
Feflow 会原生提供一个 devtool 命令


fef devtool init
   请选择你要创建的类型

fef devtool dev

**Comment by cpselvis** [comment]
已经支持，安装 0.18.0 以上版本，

fef devtool init 创建脚手架/插件
fef devtool dev 调试/插件
