### ISSUE TITLE
.feflowrc.json 冒号的指令无法被识别

### ISSUE THREAD

**Issue by brilliantGuo** [Tencent/feflow#173]
## For BUG

在 .feflowrc.json 里面用冒号的形式注册指令然后运行 fef -h 结果识别不到对应的命令

![image](https://user-images.githubusercontent.com/16346075/71446270-83cdd280-275c-11ea-96cf-574e51a60094.png)

改成 - 就可以

![image](https://user-images.githubusercontent.com/16346075/71446271-8defd100-275c-11ea-9927-0d7c9b7c208e.png)

**Comment by fXy-during** [comment]
我来处理一下

**Comment by fXy-during** [comment]
看了代码确认了，项目下关于命令的描述，也就是`.feflowrc.json`中的commands需要和套件`devkit.json`中的builders一一对应。
即`feflowrc.json`中写法为`dev:native`，套件中也需要有`dev:native`的执行器。

@brilliantGuo 悉知
