### ISSUE TITLE
支持插件的子命令描述

### ISSUE THREAD

**Issue by cpselvis** [Tencent/feflow#182]

**Comment by fXy-during** [comment]
我来支持一下

**Comment by fXy-during** [comment]
#187

**Comment by fXy-during** [comment]
该特性已在[v0.19.0-alpha.0 ](https://github.com/Tencent/feflow/releases/tag/v0.19.0-alpha.0)版本支持。 开放插件注册时registry的第四个参数，options，传入你插件参数的描述。

样例：
```js
    // 注册一个 add 命令
    context.commander.register('add',  '加法运算器',  () => { }, 
    [
        {
            name: 'help',
            description: 'Display this usage guide.',
            alias: 'h'
        }
    ]);
```

字段参考文档（关注文档中的optionList即可）： https://github.com/75lb/command-line-usage/blob/master/doc/api.md
