### ISSUE TITLE
windows10项目下运行feflow -v时会报错

### ISSUE THREAD

**Issue by cpselvis** [Tencent/feflow#19]
## For BUG
![image](https://user-images.githubusercontent.com/18289264/48978245-a322a800-f0e3-11e8-8cce-cf3b0a5777fb.png)

林江反馈：应该是操作系统的原因，在windows10 上项目的根目录执行 feflow -v 时，会弹出如下错误，我怀疑是什么机制导致你的 feflow 命令 和这个 feflow.js 建立了某些关系；因为当我cd src 里面再执行 feflow -v 时，就是正常的

**Comment by LeoEatle** [comment]
#28

**Comment by cpselvis** [comment]
这个Bug确实存在，windows 10下运行 feflow 时会优先找 feflow.js 这个文件导致的

**Comment by cpselvis** [comment]
在 v0.15.2 版本修复掉

**Comment by cpselvis** [comment]
Feflow 的项目下的配置文件准备做一个修改，目前是 feflow.json 和 feflow.js，按优先级修改成：

feflowrc.js 
feflowrc.yaml 
feflowrc.yml 
feflowrc.json

**Comment by cpselvis** [comment]
已经解决。 v0.16.0 版本将配置文件名称改成了 .feflowrc.js/.feflowrc.yml/.feflowrc.json 中的一种，不再会出现这个问题。
