### ISSUE TITLE
希望能支持将 feflow cli 工具+特定开发套件打包成可以直接执行的二进制包

### ISSUE THREAD

**Issue by cpselvis** [Tencent/feflow#193]
内部终端组件平台接入 feflow 的反馈 issue

## 需求背景
希望基于 feflow 开发面向客户端、后台的业务开发套件。而然客户端、后台同学对配置node、tnpm环境不熟悉，希望能提供包含 `feflow cli 工具`+`特定开发套件`+`配置好tnpm环境`的二进制包，供非前端同学快速上手，减少非前端同学的认知负担。

## 业界参考
开源 cli 框架 [oclif](https://oclif.io) 提供了 [多种发布方式](https://oclif.io/docs/releasing#standalone-tarballs) 包括但不限于 tar 压缩包、win安装包、mac安装包等，这样对于非前端同学来说可以快速安装 cli。

**Comment by xqxian** [comment]
已完成
