### ISSUE TITLE
希望给 devkit 命令开放 -v -version arg参数

### ISSUE THREAD

**Issue by rchee** [Tencent/feflow#198]
## For feature request
当前执行 devkit 定义的命令时，如果带上了 -v 参数，会自动走到版本号输出逻辑，导致自定义的命令无法使用 -v 参数。希望将这个参数开放给 devkit 的开发者

![image](https://user-images.githubusercontent.com/5948724/77499604-87711280-6e8d-11ea-8ee7-2fde137e39ca.png)

**Comment by cpselvis** [comment]
0.18.3 版本已经支持 https://github.com/Tencent/feflow/pull/199
