### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by wedcel** [Tencent/feflow#220]
![image](https://user-images.githubusercontent.com/3982317/79821510-8ca87b00-83c1-11ea-9f24-4339fd327453.png)

**Comment by cpselvis** [comment]
这个情况需要在脚手架里面运行一下 npm update 升级一下依赖，然后重新发布一个脚手架的版本就可以解决了

![image](https://user-images.githubusercontent.com/18289264/79821591-beb9dd00-83c1-11ea-81a6-ec52046e507c.png)
