### ISSUE TITLE
选择Yarn作为包管理器后，安装plugin的时候报错`install` has been replaced with `add` to add new dependencies.

### ISSUE THREAD

**Issue by Sara2009** [Tencent/feflow#221]
![image](https://user-images.githubusercontent.com/9332442/80328345-a3dbe280-8871-11ea-9cbb-0ad20081e81e.png)

**Comment by cpselvis** [comment]
+ commit https://github.com/Tencent/feflow/commit/f450bc2e36ae69f205c8de15d8840632b8837df1
