### ISSUE TITLE
运行fef init时，提示Your project config is not correct

### ISSUE THREAD

**Issue by fXy-during** [Tencent/feflow#222]
## For BUG

执行`fef init`时会有加载套件的报错

![企业微信截图_36ff7529-6ed5-4ea4-b392-df7beb5900e9](https://user-images.githubusercontent.com/26021950/80328589-52802300-8872-11ea-9445-0324b2208a06.png)

from tenten

**Comment by fXy-during** [comment]
https://github.com/Tencent/feflow/blob/master/packages/feflow-cli/src/core/devkit/loadDevkits.ts#L49

**Comment by cpselvis** [comment]
这个创建的目录下有 .feflowrc.json 配置文件吧？

**Comment by fXy-during** [comment]
> 这个创建的目录下有 .feflowrc.json 配置文件吧？

存在`.feflowrc.yml`

**Comment by cpselvis** [comment]
这个需要看看这个配置是否是 feflow 的全局配置还是当前的配置

**Comment by codetker** [comment]
fef 命令会优先读取距离当前目录最近的配置文件，如果当前目录和所有层级的父目录下都没有，那么使用默认的全局配置文件。已经优化了一下对应报错信息。
