### ISSUE TITLE
<FEAT>feflow对象挂载当面执行的命令

### ISSUE THREAD

**Issue by tiny-lin** [Tencent/feflow#224]
## For feature request

在生命周期里面，期望获取到当前执行的feflow命令，通过命令来判断是否继续执行下面逻辑，例如：
![image](https://user-images.githubusercontent.com/43535625/81527240-56d92f80-938c-11ea-8171-b36a93791d61.png)

现在还没有这个能力，能否在feflow-cli/src/cli/index.js 里增加，我试了下是OK的，可以的话帮忙加一下或者我来PR

![image](https://user-images.githubusercontent.com/43535625/81527348-956eea00-938c-11ea-8d6e-0dc6fd7430a2.png)

**Comment by cpselvis** [comment]
这个是可以支持的

**Comment by cpselvis** [comment]
已经支持，0.20.1 版本已经挂载了改对象
