### ISSUE TITLE
支持命令行直接完成feflow初始化

### ISSUE THREAD

**Issue by Vincentway** [Tencent/feflow#23]
第一次使用feflow的时候，需要交互式输入npm的registry和npm的proxy完成初始化。
但在build docker镜像的时候，不能交互式输入，所以没办法完成Feflow的初始化步骤
希望可以支持命令行直接完成初始化的功能

**Comment by cpselvis** [comment]
OK，这个本周支持，在v0.15.1版本中上线这个功能

**Comment by LeoEatle** [comment]
使用Docker似乎也是可以回答交互式问题的？
https://blog.csdn.net/leon_wzm/article/details/78260795
这个行得通么？

**Comment by Vincentway** [comment]
> 使用Docker似乎也是可以回答交互式问题的？
> https://blog.csdn.net/leon_wzm/article/details/78260795
> 这个行得通么？

尝试了一下这种方案，将Dockerfile中feflow初始化脚本改为
```
RUN sh -c '/bin/echo -e "\n\n" | feflow'
```
结果在build dockerfile的时候，第一个应答通过，第二个应答会报错
![image](https://user-images.githubusercontent.com/45058525/50381939-5b854100-06ce-11e9-9158-81136d104e94.png)

查看了下feflow源码，个人怀疑是因为feflow初始化结束退出代码是process.exit(2)，被Docker认为是脚本执行错误退出，进而导致镜像编译失败。
![image](https://user-images.githubusercontent.com/45058525/50381952-c59de600-06ce-11e9-9e40-68d408660692.png)

又尝试了下让Docker忽略退出错误
```
RUN sh -c '/bin/echo -e "\n\n" | feflow'; exit 0
```

但似乎Docker存在保护机制，虽然镜像编译成功，但错误的部分会被移除，运行该镜像还是需要初始化feflow
![image](https://user-images.githubusercontent.com/45058525/50381977-19103400-06cf-11e9-909c-a63c7618130d.png)

目前这种方案还没办法编译出初始化完成的feflow镜像，具体原因还得定位下。

**Comment by LeoEatle** [comment]
好吧，那感觉只能给`feflow init`加个参数支持一下了？
不过本来这两个问题难道不是针对厂内的同学才需要的吗？所以本来就不需要有啊
对于需要修改源地址的同学，增加个命令手动修改比较好...

**Comment by cpselvis** [comment]
这个目前其实已经有了命令了

$ feflow config set <key> <value>
不过这个命令也需要检查Feflow是否初始化过。会把这个限制去掉

**Comment by cpselvis** [comment]
v0.16.0-beta.8 版本已经支持，对应的 commit: https://github.com/Tencent/feflow/commit/b68df160e4ba7c1e06e9e05f255d3d6d1bde1d27 https://github.com/Tencent/feflow/commit/bdcea1654bfa6934128d3b7f15d807315c920822
