### ISSUE TITLE
Feflow WARN 的颜色看不清楚

### ISSUE THREAD

**Issue by cpselvis** [Tencent/feflow#263]
来自内部终端同学的反馈

## For feature request

![image](https://user-images.githubusercontent.com/18289264/83231615-5929ef00-a1be-11ea-97be-b212a7094140.png)

**Comment by codetker** [comment]
![image](https://user-images.githubusercontent.com/9033585/83384942-dc478100-a41a-11ea-9cce-16141a45bbc5.png)经测试 ，chalk orange 会比 yellow 对眼睛的亲和力好很多。
https://github.com/Tencent/feflow/pull/264

**Comment by cpselvis** [comment]
这个在深色背景下的截图也发出来看看
