### ISSUE TITLE
安装@feflow/cli 0.22版本后，执行install命令，提示该终端无法正常执行命令

### ISSUE THREAD

**Issue by zhuman1993** [Tencent/feflow#338]
## For BUG

 问题描述：安装@feflow/cli后，执行install命令，提示该终端无法正常执行命令
 操作环境：mac os系统，zsh终端
![image](https://user-images.githubusercontent.com/17695759/103653906-2344b880-4fa0-11eb-9976-37e87e5d602b.png)

## For question

 按照提示，执行source ~/.zshrc，install没有任何输出，list指令也没有结果
![image](https://user-images.githubusercontent.com/17695759/103655346-1032e800-4fa2-11eb-8df7-4ca1d6ecf076.png)

 降级到0.21.1版本后，安装正常了
![image](https://user-images.githubusercontent.com/17695759/103723479-22963b80-500d-11eb-9f7e-d903c3dfd65d.png)

**Comment by Stevenzwzhai** [comment]
rm -rf ~/.fef/package.json && cd ~/.fef && npm init
name填写为feflow-home，其余默认就好，该问题会在下一小版本修复

**Comment by Stevenzwzhai** [comment]
@feflow/cli@0.22.3已经修复

**Comment by zhuman1993** [comment]
@Stevenzwzhai 一周前我的zsh升级了，现在安装哪个版本的feflow都无法使用了，除了fef 和 fef --version 这两个命令，其他命令都无法执行，如下：
![image](https://user-images.githubusercontent.com/17695759/106553290-1346d700-6554-11eb-91c9-320b91ecc564.png)

在~/.zshrc里就会被自动加上这么一句
![image](https://user-images.githubusercontent.com/17695759/106553256-ff02da00-6553-11eb-90c2-16ab2974987e.png)

**Comment by zhuman1993** [comment]
问题已修复，会存在终端无法启动fef命令的情况，按照提示打开新的窗口或执行source 命令就可以使用了
