### ISSUE TITLE
为什么npm -g的包都被装到了@feflow/cli/bin 下面

### ISSUE THREAD

**Issue by Dullly** [Tencent/feflow#358]
## For question

 系统：MacOs

npm -g的包都被装到了@feflow/cli/bin 下面，导致命令行想使用包的时候找不到

请问如何解决，或者feflow要怎么卸载

**Comment by MrGaoGang** [comment]
> ## For question
> 系统：MacOs
> 
> npm -g的包都被装到了@feflow/cli/bin 下面，导致命令行想使用包的时候找不到
> 
> 请问如何解决，或者feflow要怎么卸载

Dullly这边是使用二进制包的方式安装的吗
