### ISSUE TITLE
插件里面找不到feflow

### ISSUE THREAD

**Issue by younth** [Tencent/feflow#377]
按照官网全局安装fef，安装 插件，运行 fef list报错：referenceError: feflow is not defined

查看代码，ctx的注入是 return require(pluginPath)(Object.assign({}, ctx, {logger: pluginLogger}));

插件并没有暴露函数，那怎么才能拿到 feflow变量呢

**Comment by xqxian** [comment]
hello抱歉，可能是外网官网的文档没有及时更新，实际上 feflow 从 v0.16.0 开始，注册插件的机制发生了变化：
![image](https://user-images.githubusercontent.com/21199814/134658053-77195b28-b3b6-4d5c-a944-d68e9a02a5af.png)

新版的插件写法可参考：https://github.com/vabaly/feflow-plugin-example/tree/dev

我们后续会更新文档，给您带来不好的使用体验非常抱歉。
