### ISSUE TITLE
执行feflow的命令时经常报错update.lock error

### ISSUE THREAD

**Issue by yuchajianshi** [Tencent/feflow#404]
执行任何feflow命令都会经常报下面这个错误，大概频率在1/3左右，报错之后再运行就没问题了

`[ Feflow Error ][ feflow-cli ] check C:\Users\username\.fef\update.lock error:  [Error: EPERM: operation 
not permitted, open 'C:\Users\username\.fef\update.lock'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\username\\.fef\\update.lock'
}
`

**Comment by xqxian** [comment]
已在此版本修复，欢迎试用哈~ https://github.com/Tencent/feflow/releases/tag/v0.26.0
