### ISSUE TITLE
运行到init之后链路就断了

### ISSUE THREAD

**Issue by erasermeng** [Tencent/feflow#46]
```
feflow init
? 请输入npm的registry: http://registry.npmjs.org
? 请输入npm的proxy(默认为空): 
Feflow INFO  初始化完成，请输入命令开启feflow的使用之旅。(帮助：feflow -h)
```

运行完init，什么也没生成，也没有变化，不知道要干什么？文档指引不够清晰

**Comment by LeoEatle** [comment]
建议不要让用户第一次使用的时候输入`registry`和`proxy`了，外部用户都是用不到的。直接默认的就好。
如果需要设置，弄个`feflow config`

**Comment by cpselvis** [comment]
有道理，采纳。首次进入不需要进行配置registry和proxy，通过配置的方式进行

**Comment by cpselvis** [comment]
目前已经优化了使用方式，每次进来不用手动输入 registry 和 proxy，会自动检测本地已经安装的包管理工具。

**Comment by Stevenzwzhai** [comment]
已经解决
