### ISSUE TITLE
feflow 所有命令报错问题

### ISSUE THREAD

**Issue by shenzekun** [Tencent/feflow#72]
## For BUG

当第一次使用 feflow 的时候
出现输入 register，但是这个 register 可能有用户输入出错，比如
![image](https://user-images.githubusercontent.com/21151080/52949048-289db780-33b6-11e9-841b-2c000913ff07.png)

现在使用`feflow -h`，出现
![image](https://user-images.githubusercontent.com/21151080/52949094-49fea380-33b6-11e9-9123-2ba7fae76315.png)

这个时候，想要使用 `feflow config` 重新设置正确的 register，但是还是出现如下（设置register失效）：
![image](https://user-images.githubusercontent.com/21151080/52949197-90540280-33b6-11e9-89f3-f5598dd35633.png)

使用其他命令
![image](https://user-images.githubusercontent.com/21151080/52949279-cabd9f80-33b6-11e9-9bbb-aab6002306b9.png)

也就是说第一次用户如果输入 register 错误的话，将会导致一切命令都失效，重新设置都无效，必须将`~/.feflow`目录删除，才能重新输入正确的 register。建议添加一些容错处理。

**Comment by cpselvis** [comment]
这个已经优化了，v0.16.0 版本会自动识别用户安装的 npm、tnpm、yarn 等工具
