### ISSUE TITLE
feflow init 本地代理存在问题时，提示信息需要优化

### ISSUE THREAD

**Issue by chyingp** [Tencent/feflow#97]
## For BUG

本地代理存在问题时，运行`feflow init`，会经过两个步骤，两个步骤之间间隔时间较长

1. 界面没有任何提示，30s+
![image](https://user-images.githubusercontent.com/2383346/59574673-c4340000-90ea-11e9-9a46-d170e301e437.png)

2. 提示更新，最后失败
![image](https://user-images.githubusercontent.com/2383346/59574695-d44bdf80-90ea-11e9-9370-dd21da9f1364.png)

**Comment by cpselvis** [comment]
已经优化，0.16.0 版本不再需要通过输入 registry 的方式。

可以试试：
```
$ npm i @feflow/cli -g
$ fef init
```
